perm_years_fn<- function(n, block_size = BLOCK_SIZE){
  # Generates a matrix of 999 random permutations, with non-repeating rows, of the given labels
  
  perm_matrix<- matrix(NA, nrow = NPERM, ncol = n)
  if (!is.null(BLOCK_SIZE)){
    shifter <- function(x, a) {
      if (a == 0) x else c(tail(x, -a), head(x, a))
    }
    for(i in 1:(NPERM-1)){
      time_series<- shifter(1:n, sample(0:(n-1),1))
      blocks<- split(time_series, ceiling(seq_along(time_series)/BLOCK_SIZE))
      if(length(blocks[[length(blocks)]]) < BLOCK_SIZE) {
        blocks[[(length(blocks)-1)]]<-  c(blocks[[(length(blocks)-1)]],  blocks[[length(blocks)]])
        blocks[[length(blocks)]]<- NULL
      }
      tmp<- blocks # lapply(blocks, sample)
      perm_matrix[i,]<- unname(unlist(tmp[sample.int(length(blocks))]))  # unname(unlist(tmp))
    }
    perm_matrix[NPERM,]<- 1:n # original my_data ( years in order, actual numbers dont really matter, ie 1:10 vs 1981:1990)
    while(sum(duplicated(perm_matrix))>0){
      sel<- which(duplicated(perm_matrix, fromLast = TRUE)) #From last makes last row (original results) stay...
      for (i in 1:length(sel)) {
        time_series<- shifter(1:n, sample(0:(n-1),1))
        blocks<- split(time_series, ceiling(seq_along(time_series)/BLOCK_SIZE))
        if(length(blocks[[length(blocks)]]) < BLOCK_SIZE) {
          blocks[[(length(blocks)-1)]]<-  c(blocks[[(length(blocks)-1)]],  blocks[[length(blocks)]])
          blocks[[length(blocks)]]<- NULL
        }
        tmp<- blocks # lapply(blocks, sample)
        perm_matrix[sel[i],]<- unname(unlist(tmp[sample.int(length(blocks))]))
      }
    }
    return(perm_matrix)
  } else{
    
    for(i in 1:(NPERM-1)){
      perm_matrix[i,]<- sample.int(n)
    }
    perm_matrix[NPERM,]<- 1:n # original my_data ( years in order, actual numbers dont really matter, ie 1:10 vs 1981:1990)
    
    while(sum(duplicated(perm_matrix))>0){
      sel<- which(duplicated(perm_matrix, fromLast = TRUE)) #From last makes last row (original results) stay...
      for (i in 1:length(sel)) perm_matrix[sel[i],]<- sample.int(n) 
    }
    return(perm_matrix)
  }
}

perm_distr_trend_fn<- function(my_data){
  # this function is for trend detection
  # input is object generated by list_to_matrix_function
  Y<- my_data$Y
  num_years<- nrow(Y)
  
  if (num_years<7){ stop('not enough observations, minimum 7 required')
  } else{perm_matrix<- perm_years_fn(num_years)}
    
  # trends<- apply(Y, 2, sen0)
  # Y_detrend<- matrix(NA, ncol = ncol(Y), nrow = nrow(Y))
  # for(i in 1:ncol(Y)) Y_detrend[,i]<- Y[,i] - trends[i]*(1:(nrow(Y)))
  #Creating vectors to store max at each permutation
  mk_stat<- vector(length = NPERM) 
  mk_max_cluster<- vector(length = NPERM)
  
  print("generating permutation distributions")
  for (i in 1:NPERM){
    # trend free permuting - doesnt seem to work
    # Y_perm<- Y_detrend[perm_matrix[i,],]
    # for(j in 1:ncol(Y)) Y_perm[,j]<- Y_perm[,j] + trends[j]*(1:(nrow(Y)))
    
    Y_perm<- Y[perm_matrix[i,],]
    
    results<- apply(Y_perm, 2, mk_z_stat_fn)
    mk_stat[i]<- max(abs(results), na.rm = TRUE)
    mk_max_cluster[i]<- max_cluster_fn(results, all.results = FALSE, my_data)
    if (i%%10 == 0) print(i)
  }
  return(list(mk_stat = mk_stat, mk_max_cluster = mk_max_cluster, original_res = results))
}

perm_distr_trend_fn_mclapply<- function(my_data){
  # this function is for trend detection
  # input is object generated by list_to_matrix_function
  Y<- my_data$Y
  num_years<- nrow(Y)
  
  if (num_years<7){ stop('not enough observations, minimum 7 required')
  } else{perm_matrix<- perm_years_fn(num_years)}
  
  # trends<- apply(Y, 2, sen0)
  # Y_detrend<- matrix(NA, ncol = ncol(Y), nrow = nrow(Y))
  # for(i in 1:ncol(Y)) Y_detrend[,i]<- Y[,i] - trends[i]*(1:(nrow(Y)))
  #Creating vectors to store max at each permutation
 
  print("generating permutation distributions")
  tmp_fn<- function(i, perm_matrix, Y){
    Y_perm<- Y[perm_matrix[i,],]
      results<- apply(Y_perm, 2, mk_z_stat_fn)
    mk_stat<- max(abs(results), na.rm = TRUE)
    mk_max_cluster<- max_cluster_fn(results, all.results = FALSE, my_data)
    if(i%%10 == 0) print(i)
    return(c(mk_stat = mk_stat, mk_max_cluster = mk_max_cluster))
  }
  results<- mclapply(1:NPERM, tmp_fn, perm_matrix = perm_matrix, Y = Y, mc.cores = NCORES, mc.preschedule = FALSE)
  results<- do.call(rbind, results)
  mk_stat<- results[,1]
  mk_max_cluster<- results[,2]
  return(list(mk_stat = mk_stat, mk_max_cluster = mk_max_cluster))
}
